
title: Welcome to my GitHub page!
description: I'm a science journalist studying data visualization and experience design with my classmates at Northeastern University. Please watch this space to follow our explorations in data-driven design for the web.
